### ISSUE TITLE
dynamically add classpath as in babashka

### ISSUE THREAD

**Issue by xfthhxk** [babashka/nbb#100]
**Is your feature request related to a problem? Please describe.**
I'd like to dynamically add to the classpath as in babashka.

**Describe the solution you'd like**
The equivalent of `babashka.claspath/add-classpath`

**Describe alternatives you've considered**
Currently, it is possible to `nbb --classpath directory script.cljs`.  Also discovered 
the ability to do the following which is a workaround for executable scripts:

```shell
#!/usr/bin/env -S nbb --classpath src
```
However for the above `env` approach to work, you must be in the same directory as the executable.

**Comment by borkdude** [comment]
From slack:

9:58 PM
borkdude:clj-kondo: @amar I was thinking, we could add add-classpath to nbb.core and then you could even distribute a script which you can publish on npm, so you can do npx unminify <input> <source-map>
9:59 PM
and your src/*.cljs files would then live in node_modules/unminify/src which you can dynamically add to the classpath using
(add-classpath (path/parent *file* "src")) 
9:59 PM
amar That would be pretty sweet
10:01 PM
borkdude:clj-kondo: This script would actually be a small .js file which does loadFile("unminify") which you can then add to you npm package.json as a bin(ary)
10:01 PM
and then it should all work via npm / npx (edited) 
New
10:02 PM
amar Cool. I will have to grok some of that since I'm still new to the node world but I definitely like the sound of what you suggested
10:03 PM
borkdude:clj-kondo: @amar I will make an example soon

**Comment by borkdude** [comment]
Already implemented as `nbb.classpath/add-classpath`
