### ISSUE TITLE
Error when using extend-protocol

### ISSUE THREAD

**Issue by xfthhxk** [babashka/nbb#103]
**version**
0.0.109

**platform**
Ubuntu 20.04, node v16.13.0

**problem**
`nbb` appears to throw an error when it encounteres `extend-protocol`. 
```
Message:  No protocol method IDeref.-deref defined for type null:
Location: /home/foo/nbb-protocol-issue/eg.cljs:6:1
```
**repro**
https://github.com/xfthhxk/nbb-protocol-issue

**expected behavior**
`extend-protocol` should not throw an error

**Comment by borkdude** [comment]
Currently SCI doesn't expose `ILookup` as a protocol. What would be necessary for this is to patch all functions that are are transitively related to `ILookup` such as `-lookup`, `get`, etc. And there are just too many functions that use `get`: this would make it both a lot of work to patch them all, and it will incur an extra performance penalty.

I think it's better to just write your own accessor function in nbb rather than trying to extend `ILookup` in nbb.
