### ISSUE TITLE
0.6.124 has a regression for cljs.test/assert-expr

### ISSUE THREAD

**Issue by logseq-cldwalker** [babashka/nbb#234]
Hey @borkdude. Noticed this regression while looking to bump nbb-logseq to latest nbb

**version**

0.6.124

**platform**

osx 12.0.1 and node 16.13.1

**problem**

When bumping [nbb-features to latest nbb](https://github.com/babashka/nbb-features/commit/eaf82b2910bccfc84ed7430d6ce6864bfd9a8e68), CI fails on [this line](https://github.com/babashka/nbb-features/runs/7304362783?check_suite_focus=true#step:6:17) with exception `Message:  No protocol method IMultiFn.-add-method defined for type function:`

**repro**

```
nbb -e "(require '[cljs.test :as t]) (defmethod t/assert-expr 'thrown-msg? [menv msg form] nil)"
```

**expected behavior**

I expected nbb-feature tests to run like they did for [nbb 0.5.103](https://github.com/babashka/nbb-features/runs/6457501402?check_suite_focus=true)

**Comment by borkdude** [comment]
I'll look into it tomorrow.

**Comment by logseq-cldwalker** [comment]
@borkdude Thanks for the fix! I bumped to 0.6.125 and ran into a cryptic [Could not resolve symbol: G__107](https://github.com/babashka/nbb-features/runs/7321947480?check_suite_focus=true#step:6:10). I was able [to work around this](https://github.com/babashka/nbb-features/commit/912ca86f1744b80d58d2c5c613df3a77d9f8624e) by changing the `t/assert-expr` to have [4 args like sci expects](https://github.com/babashka/sci.configs/blob/3eed9938d0f3b76326ed81005c5ac9e5d6aeca3a/src/sci/configs/cljs/test.cljs#L534-L539) instead of the [3 args cljs expects](https://github.com/clojure/clojurescript/blob/e7cdc70d0371a26e07e394ea9cd72d5c43e5e363/src/main/cljs/cljs/test.cljc#L76-L81). Is there a place where you want to documents differences between nbb and cljs behavior like this? This was tricky to track down and I could see this biting others

**Comment by borkdude** [comment]
@logseq-cldwalker The issue is this:

SCI needs to pass the context to this multimethod 

https://github.com/babashka/sci.configs/blob/3eed9938d0f3b76326ed81005c5ac9e5d6aeca3a/src/sci/configs/cljs/test.cljs#L535

since the context is used here:

https://github.com/babashka/sci.configs/blob/3eed9938d0f3b76326ed81005c5ac9e5d6aeca3a/src/sci/configs/cljs/test.cljs#L547

And there is a special field in a SCI var which indicates that the interpreter should pass the context as the first argument when it's called. This should be invisible to the code.

But I didn't realize that when you implement this multi-method, that the user does in fact has to provide the corresponding arity.

The automatic context passing might not work so good here. Another alternative might be to let sci.configs or sci itself have the idea of a global context (atom or so) so that libraries like sci.configs can use that instead.

**Comment by borkdude** [comment]
The previous issue also resulted from this: since the context needed to be passed, the multimethod was wrapped with` (partial multi-fn ctx)` which made it not a multimethod anymore.

**Comment by borkdude** [comment]
So perhaps `sci.core` can introduce a `*ctx*` dynamic var and `(set-ctx! ...) so the var can be set to a global context. Then sci.configs can use that context and require the user to call `set-ctx!` first. A dynamic var so multiple threads can use different contexts on the JVM. When we have that I can reliably solve the above problem.

**Comment by logseq-cldwalker** [comment]
I'm ok with whatever you solution you'd prefer. Agree that the more compatible the end solution is with clj/cljs the better. 

> require the user to call set-ctx! first
I'm guessing this is a sci user in which case the nbb experience is indeed better

**Comment by borkdude** [comment]
Yes, indeed, it's a SCI config thing, not something the script writer would see.

**Comment by logseq-cldwalker** [comment]
Confirmed this works as intended on nbb-features - https://github.com/babashka/nbb-features/runs/7344301638?check_suite_focus=true . Thanks!
