### ISSUE TITLE
Add tools.cli as optional module

### ISSUE THREAD

**Issue by borkdude** [babashka/nbb#58]
Moreover, it would be nice if this entire project could run with nbb:

https://github.com/wildwestrom/uniorg-util

/cc @wildwestrom

**Comment by logseq-cldwalker** [comment]
Two reasons why having tools.cli would be nice to have as part of nbb:

* Makes it easier to reuse or transition a script from bb to nbb. At work, I started a script (github action) with bb and then as I'm adding more features I'm considering moving to nbb because there are more libraries in npm to choose from
* I wrote a [node test runner](https://github.com/logseq/logseq/blob/bd9f47a2a06109f05d9a866ceb2d3c1248575bd0/src/test/frontend/node_test_runner.cljs#L16-L83) that provides the same test selection options as https://github.com/cognitect-labs/test-runner but it relies on tools.cli. Happy to provide it to nbb if interested

**Comment by borkdude** [comment]
@logseq-cldwalker I think it's a no-brainer. PR for optional tools.cli module welcome.

**Comment by logseq-cldwalker** [comment]
Cool. Is https://github.com/babashka/nbb/commit/9d03c524c967513b163885cc1dba33e241dea7ca a good example of all the files that need to be updated when adding a library?

**Comment by borkdude** [comment]
Indeed. In `script/nbb_tests.clj` there are also some integration tests. Would be nice to add a few there for tools.cli.

**Comment by borkdude** [comment]
Tools cli is now included.

**Comment by logseq-cldwalker** [comment]
Thanks!
